use_frameworks!

platform :ios, '8.0'

target 'OCastExample-Swift' do
    pod 'OCast', :path => '../'
    pod 'OCastReferenceDriver', :git => 'https://github.com/Orange-OpenSource/OCastReferenceDriver-iOS.git', :branch => 'master'

  target 'OCast_Tests' do
    inherit! :search_paths
  end
  
end

target 'OCastExample-ObjC' do
    pod 'OCast', :path => '../'
    pod 'OCastReferenceDriver', :git => 'https://github.com/Orange-OpenSource/OCastReferenceDriver-iOS.git', :branch => 'master'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # add some macros for the compiler
            gcc_macros = ["$(inherited)"]
            swift_conditions = ["$(inherited)"]
            if config.name != "Release"
                swift_conditions.push("DEBUG")
            end
            if gcc_macros.count > 1
                config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] ||= gcc_macros
            end
            if swift_conditions.count > 1
                config.build_settings["SWIFT_ACTIVE_COMPILATION_CONDITIONS"] ||= swift_conditions
            end
        end
    end
end
