opt_in_rules:
  - closure_spacing
    #- multiline_arguments # Disabled because of closures as arguments
  - multiline_parameters
  - let_var_whitespace
  - operator_usage_whitespace
  - literal_expression_end_indentation
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - switch_case_alignment
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

disabled_rules:
  - line_length
  - identifier_name
  
type_body_length:
  warning: 500
  error: 600

file_length:
  warning: 800
  error: 900

type_name:
  max_length: 50

function_parameter_count:
  warning: 7
  error: 10
  
excluded:
  - Pods
  - build

trailing_whitespace:
  ignores_empty_lines: true
