osx_image: xcode10.2
language: swift

branches:
  only:
    - master
    - 2.0
    - /^2.0_.*$

before_install:
    - gem install bundler
install:
    - bundle install
    - bundle exec pod install --repo-update

script:
  - set -o pipefail
  - xcodebuild build -workspace OCast.xcworkspace -scheme OCast -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7,OS=latest" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -s
  - xcodebuild test -workspace OCast.xcworkspace -scheme 'OCastTests' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=latest' | xcpretty -s
  - xcodebuild build -workspace OCast.xcworkspace -scheme OCastDemoSwift -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7,OS=latest" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -s
  - xcodebuild build -workspace OCast.xcworkspace -scheme OCastDemoObjC -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 7,OS=latest" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -s
